import type {
  AgentRoleDefinition,
  DepartmentDefinition,
  RoleId
} from "../../../shared/src/index.js";

export const DEPARTMENTS = [
  {
    id: "executive",
    name: "Executive",
    purpose: "Own mission outcome, operating strategy, and final accountability.",
    roomTheme: "board room with mission screens"
  },
  {
    id: "product",
    name: "Product and Analysis",
    purpose: "Turn user goals into clear scope, requirements, and acceptance criteria.",
    roomTheme: "planning room with story wall"
  },
  {
    id: "design",
    name: "Design",
    purpose: "Shape workflows, UI states, accessibility, and UX copy.",
    roomTheme: "design studio with screen boards"
  },
  {
    id: "engineering",
    name: "Engineering",
    purpose: "Design and implement technical changes across code, data, and integrations.",
    roomTheme: "development floor with paired workstations"
  },
  {
    id: "qa",
    name: "QA Lab",
    purpose: "Verify behavior, regressions, security, performance, and accessibility.",
    roomTheme: "test lab with devices and automation rigs"
  },
  {
    id: "devops",
    name: "DevOps and Reliability",
    purpose: "Run CI/CD, deployment, monitoring, rollback, and environment safety.",
    roomTheme: "release control room with pipeline displays"
  },
  {
    id: "operations",
    name: "Company Operations",
    purpose: "Manage capacity, cost, compliance, customer communication, docs, and memory.",
    roomTheme: "operations office with records and dashboards"
  }
] as const satisfies readonly DepartmentDefinition[];

const commonReadTools = ["mission_context", "artifact_store", "audit_log", "task_graph", "knowledge_base"] as const;
const planningTools = [...commonReadTools, "issue_tracker", "knowledge_base"] as const;
const engineeringTools = [
  ...commonReadTools,
  "repo_search",
  "file_read",
  "file_write",
  "shell_command",
  "test_runner"
] as const;
const qaTools = [...commonReadTools, "repo_search", "file_read", "test_runner", "browser_check"] as const;
const devopsTools = [
  ...commonReadTools,
  "ci_status",
  "git_branch",
  "git_commit",
  "pull_request",
  "deploy_staging",
  "monitoring"
] as const;

export const ROLE_REGISTRY = [
  {
    id: "ceo",
    name: "CEO Agent",
    department: "executive",
    level: "executive",
    responsibilities: ["Own final mission outcome", "Resolve executive conflicts", "Approve final report"],
    defaultTools: [...commonReadTools, "cost_records"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "executive.decision.v1",
    promptTemplateId: "executive.ceo.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Edit code directly", "Override QA evidence without an audit record"]
  },
  {
    id: "coo",
    name: "COO Agent",
    department: "executive",
    level: "executive",
    responsibilities: ["Coordinate department handoffs", "Track blockers", "Own operating plan"],
    defaultTools: [...commonReadTools, "cost_records"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "operations.plan.v1",
    promptTemplateId: "executive.coo.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Deploy without release gate", "Hide blockers from final report"]
  },
  {
    id: "cto",
    name: "CTO Agent",
    department: "executive",
    level: "executive",
    responsibilities: ["Own technical direction", "Approve architecture risk", "Resolve technical tradeoffs"],
    defaultTools: [...commonReadTools, "repo_search", "file_read"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "technical.strategy.v1",
    promptTemplateId: "executive.cto.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Approve implementation without Tech Lead or QA evidence"]
  },
  {
    id: "cpo",
    name: "CPO Agent",
    department: "executive",
    level: "executive",
    responsibilities: ["Own product value", "Approve scope", "Resolve acceptance criteria conflicts"],
    defaultTools: planningTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "product.scope.v1",
    promptTemplateId: "executive.cpo.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Approve technical architecture alone"]
  },
  {
    id: "chief_of_staff",
    name: "Chief of Staff Agent",
    department: "executive",
    level: "lead",
    responsibilities: ["Maintain status integrity", "Summarize mission progress", "Verify final narrative"],
    defaultTools: [...commonReadTools, "knowledge_base"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "status.summary.v1",
    promptTemplateId: "executive.chief_of_staff.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Invent completion status without artifact evidence"]
  },
  {
    id: "engineering_director",
    name: "Engineering Director Agent",
    department: "executive",
    level: "lead",
    responsibilities: ["Allocate engineering roles", "Balance delivery capacity", "Escalate engineering blockers"],
    defaultTools: [...commonReadTools, "role_registry"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "engineering.allocation.v1",
    promptTemplateId: "executive.engineering_director.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Merge or deploy code"]
  },
  {
    id: "product_manager",
    name: "Product Manager Agent",
    department: "product",
    level: "lead",
    responsibilities: ["Write PRD", "Set scope in and out", "Define acceptance criteria"],
    defaultTools: planningTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "product.prd.v1",
    promptTemplateId: "product.pm.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Approve code quality", "Change architecture without CTO or Tech Lead"]
  },
  {
    id: "project_manager",
    name: "Project Manager Agent",
    department: "product",
    level: "staff",
    responsibilities: ["Track timeline", "Manage dependencies", "Report delivery progress"],
    defaultTools: planningTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "delivery.timeline.v1",
    promptTemplateId: "product.project_manager.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Approve quality gate alone"]
  },
  {
    id: "scrum_master",
    name: "Scrum Master Agent",
    department: "product",
    level: "staff",
    responsibilities: ["Surface blockers", "Keep work moving", "Maintain retry and escalation cadence"],
    defaultTools: planningTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "delivery.blockers.v1",
    promptTemplateId: "product.scrum_master.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Change scope without PM"]
  },
  {
    id: "lead_ba",
    name: "Lead BA Agent",
    department: "product",
    level: "lead",
    responsibilities: ["Own business rules", "Create acceptance matrix", "Review requirement completeness"],
    defaultTools: planningTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "analysis.business_rules.v1",
    promptTemplateId: "product.lead_ba.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Deploy or merge code", "Override technical feasibility"]
  },
  {
    id: "business_analyst",
    name: "Business Analyst Agent",
    department: "product",
    level: "staff",
    responsibilities: ["Detail requirements", "Find edge cases", "Map validation rules"],
    defaultTools: planningTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "analysis.requirements.v1",
    promptTemplateId: "product.business_analyst.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Approve own requirements"]
  },
  {
    id: "ux_researcher",
    name: "UX Researcher Agent",
    department: "product",
    level: "specialist",
    responsibilities: ["Identify user assumptions", "Map journeys", "Find usability risks"],
    defaultTools: planningTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "research.user_journey.v1",
    promptTemplateId: "product.ux_researcher.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Invent research evidence as fact"]
  },
  {
    id: "data_analyst",
    name: "Data Analyst Agent",
    department: "product",
    level: "specialist",
    responsibilities: ["Define metrics", "Review data needs", "Create event taxonomy"],
    defaultTools: planningTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "analysis.metrics.v1",
    promptTemplateId: "product.data_analyst.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Change database schema directly"]
  },
  {
    id: "product_designer",
    name: "Product Designer Agent",
    department: "design",
    level: "lead",
    responsibilities: ["Own UX flow", "Shape screen behavior", "Map interaction states"],
    defaultTools: [...planningTools, "browser_check"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "design.flow.v1",
    promptTemplateId: "design.product_designer.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Approve accessibility alone"]
  },
  {
    id: "ui_designer",
    name: "UI Designer Agent",
    department: "design",
    level: "staff",
    responsibilities: ["Design UI states", "Apply visual system", "Keep hierarchy readable"],
    defaultTools: [...planningTools, "browser_check"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "design.ui_states.v1",
    promptTemplateId: "design.ui_designer.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Use pixel fonts for functional UI text"]
  },
  {
    id: "design_system_designer",
    name: "Design System Designer Agent",
    department: "design",
    level: "specialist",
    responsibilities: ["Own tokens", "Maintain component consistency", "Review UI states"],
    defaultTools: [...planningTools, "browser_check"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "design.system.v1",
    promptTemplateId: "design.system_designer.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Invent a second visual vocabulary"]
  },
  {
    id: "ux_writer",
    name: "UX Writer Agent",
    department: "design",
    level: "specialist",
    responsibilities: ["Write labels", "Write error states", "Write empty states and final user-facing text"],
    defaultTools: planningTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "design.ux_copy.v1",
    promptTemplateId: "design.ux_writer.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Use vague marketing copy in product UI"]
  },
  {
    id: "solution_architect",
    name: "Solution Architect Agent",
    department: "engineering",
    level: "lead",
    responsibilities: ["Define system boundaries", "Select architecture path", "Review integration design"],
    defaultTools: [...engineeringTools, "knowledge_base"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "technical.architecture.v1",
    promptTemplateId: "engineering.solution_architect.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: true,
    mustNotDo: ["Implement broad changes without task ownership"]
  },
  {
    id: "tech_lead",
    name: "Tech Lead Agent",
    department: "engineering",
    level: "lead",
    responsibilities: ["Own implementation plan", "Review code quality", "Approve implementation gate"],
    defaultTools: [...engineeringTools, "browser_check"],
    permissionClasses: ["read", "draft", "write_local"],
    outputSchemaId: "technical.implementation_plan.v1",
    promptTemplateId: "engineering.tech_lead.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: true,
    mustNotDo: ["Sign off without QA evidence"]
  },
  {
    id: "fullstack_developer",
    name: "Fullstack Developer Agent",
    department: "engineering",
    level: "staff",
    responsibilities: ["Implement cross-layer features", "Map UI/API contracts", "Produce code patch"],
    defaultTools: engineeringTools,
    permissionClasses: ["read", "draft", "write_local"],
    outputSchemaId: "implementation.fullstack.v1",
    promptTemplateId: "engineering.fullstack.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Approve own implementation"]
  },
  {
    id: "frontend_developer",
    name: "Frontend Developer Agent",
    department: "engineering",
    level: "staff",
    responsibilities: ["Implement UI components", "Handle client state", "Preserve accessibility"],
    defaultTools: [...engineeringTools, "browser_check"],
    permissionClasses: ["read", "draft", "write_local"],
    outputSchemaId: "implementation.frontend.v1",
    promptTemplateId: "engineering.frontend.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Change backend contracts without Tech Lead"]
  },
  {
    id: "backend_developer",
    name: "Backend Developer Agent",
    department: "engineering",
    level: "staff",
    responsibilities: ["Implement APIs", "Build services", "Maintain server-side contracts"],
    defaultTools: engineeringTools,
    permissionClasses: ["read", "draft", "write_local"],
    outputSchemaId: "implementation.backend.v1",
    promptTemplateId: "engineering.backend.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Change product behavior without PM/BA trace"]
  },
  {
    id: "database_engineer",
    name: "Database Engineer Agent",
    department: "engineering",
    level: "specialist",
    responsibilities: ["Design schema", "Review indexes", "Create migrations"],
    defaultTools: engineeringTools,
    permissionClasses: ["read", "draft", "write_local"],
    outputSchemaId: "implementation.database.v1",
    promptTemplateId: "engineering.database.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Run destructive migration without release gate"]
  },
  {
    id: "ai_ml_engineer",
    name: "AI/ML Engineer Agent",
    department: "engineering",
    level: "specialist",
    responsibilities: ["Design agent behavior", "Route models", "Review AI reliability"],
    defaultTools: [...engineeringTools, "knowledge_base"],
    permissionClasses: ["read", "draft", "write_local"],
    outputSchemaId: "implementation.ai_behavior.v1",
    promptTemplateId: "engineering.ai_ml.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Store raw secrets or unverified memory"]
  },
  {
    id: "prompt_engineer",
    name: "Prompt Engineer Agent",
    department: "engineering",
    level: "specialist",
    responsibilities: ["Write role prompts", "Create eval cases", "Improve structured outputs"],
    defaultTools: [...commonReadTools, "knowledge_base"],
    permissionClasses: ["read", "draft", "write_local"],
    outputSchemaId: "implementation.prompt.v1",
    promptTemplateId: "engineering.prompt_engineer.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Change prompts without benchmark coverage"]
  },
  {
    id: "integration_engineer",
    name: "Integration Engineer Agent",
    department: "engineering",
    level: "specialist",
    responsibilities: ["Connect external APIs", "Handle webhooks", "Document integration contracts"],
    defaultTools: engineeringTools,
    permissionClasses: ["read", "draft", "write_local"],
    outputSchemaId: "implementation.integration.v1",
    promptTemplateId: "engineering.integration.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Expose credentials in logs"]
  },
  {
    id: "qa_lead",
    name: "QA Lead Agent",
    department: "qa",
    level: "lead",
    responsibilities: ["Own verification strategy", "Approve QA gate", "Triage defects"],
    defaultTools: qaTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "qa.strategy.v1",
    promptTemplateId: "qa.lead.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: true,
    mustNotDo: ["Change product scope without PM"]
  },
  {
    id: "manual_qa",
    name: "Manual QA Agent",
    department: "qa",
    level: "staff",
    responsibilities: ["Explore behavior", "Record reproduction steps", "Compare against acceptance criteria"],
    defaultTools: qaTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "qa.manual.v1",
    promptTemplateId: "qa.manual.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Mark untested behavior as passed"]
  },
  {
    id: "automation_qa",
    name: "Automation QA Agent",
    department: "qa",
    level: "staff",
    responsibilities: ["Write automated tests", "Run regression checks", "Report test evidence"],
    defaultTools: [...qaTools, "file_write", "shell_command"],
    permissionClasses: ["read", "draft", "write_local"],
    outputSchemaId: "qa.automation.v1",
    promptTemplateId: "qa.automation.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Ignore failing tests without defect record"]
  },
  {
    id: "security_qa",
    name: "Security QA Agent",
    department: "qa",
    level: "specialist",
    responsibilities: ["Check auth risk", "Review secret handling", "Find security regressions"],
    defaultTools: qaTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "qa.security.v1",
    promptTemplateId: "qa.security.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: true,
    mustNotDo: ["Approve risky release without Security Engineer"]
  },
  {
    id: "performance_qa",
    name: "Performance QA Agent",
    department: "qa",
    level: "specialist",
    responsibilities: ["Check performance risks", "Review bottlenecks", "Report timing evidence"],
    defaultTools: qaTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "qa.performance.v1",
    promptTemplateId: "qa.performance.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Claim performance pass without measurement"]
  },
  {
    id: "accessibility_qa",
    name: "Accessibility QA Agent",
    department: "qa",
    level: "specialist",
    responsibilities: ["Check WCAG risks", "Verify keyboard and screen-reader paths", "Review contrast"],
    defaultTools: qaTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "qa.accessibility.v1",
    promptTemplateId: "qa.accessibility.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: true,
    mustNotDo: ["Approve inaccessible UI because it looks good"]
  },
  {
    id: "devops_lead",
    name: "DevOps Lead Agent",
    department: "devops",
    level: "lead",
    responsibilities: ["Own CI/CD plan", "Prepare release gate", "Coordinate deploy safety"],
    defaultTools: devopsTools,
    permissionClasses: ["read", "draft", "write_remote", "deploy_staging"],
    outputSchemaId: "devops.plan.v1",
    promptTemplateId: "devops.lead.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: true,
    mustNotDo: ["Deploy code that failed QA gate"]
  },
  {
    id: "sre",
    name: "SRE Agent",
    department: "devops",
    level: "specialist",
    responsibilities: ["Validate health checks", "Monitor release", "Trigger rollback signal"],
    defaultTools: [...devopsTools, "monitoring"],
    permissionClasses: ["read", "draft", "deploy_staging"],
    outputSchemaId: "devops.health.v1",
    promptTemplateId: "devops.sre.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: true,
    mustNotDo: ["Hide incident signals"]
  },
  {
    id: "cloud_architect",
    name: "Cloud Architect Agent",
    department: "devops",
    level: "specialist",
    responsibilities: ["Review cloud topology", "Plan infrastructure", "Assess runtime risk"],
    defaultTools: devopsTools,
    permissionClasses: ["read", "draft"],
    outputSchemaId: "devops.cloud_architecture.v1",
    promptTemplateId: "devops.cloud_architect.v1",
    canCreateTasks: true,
    canApprovePhaseGate: false,
    canRunExternalTools: true,
    mustNotDo: ["Change infrastructure without release policy"]
  },
  {
    id: "release_manager",
    name: "Release Manager Agent",
    department: "devops",
    level: "lead",
    responsibilities: ["Approve release readiness", "Own release notes", "Coordinate rollback plan"],
    defaultTools: devopsTools,
    permissionClasses: ["read", "draft", "write_remote", "deploy_staging"],
    outputSchemaId: "release.readiness.v1",
    promptTemplateId: "devops.release_manager.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: true,
    mustNotDo: ["Release without rollback visibility"]
  },
  {
    id: "security_engineer",
    name: "Security Engineer Agent",
    department: "devops",
    level: "specialist",
    responsibilities: ["Review runtime security", "Own access risk", "Block unsafe releases"],
    defaultTools: [...devopsTools, "repo_search", "secret_reference"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "security.runtime.v1",
    promptTemplateId: "devops.security_engineer.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: true,
    mustNotDo: ["Expose secrets", "Approve critical security risk without audit"]
  },
  {
    id: "hr_manager",
    name: "HR Manager Agent",
    department: "operations",
    level: "specialist",
    responsibilities: ["Plan role capacity", "Track agent load", "Recommend staffing changes"],
    defaultTools: [...commonReadTools, "role_registry"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "ops.capacity.v1",
    promptTemplateId: "operations.hr_manager.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Change mission scope"]
  },
  {
    id: "finance_manager",
    name: "Finance Manager Agent",
    department: "operations",
    level: "specialist",
    responsibilities: ["Track costs", "Warn on budget risk", "Compare estimate to actual"],
    defaultTools: [...commonReadTools, "cost_records"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "ops.cost.v1",
    promptTemplateId: "operations.finance_manager.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Block mission silently without cost evidence"]
  },
  {
    id: "legal_compliance_agent",
    name: "Legal/Compliance Agent",
    department: "operations",
    level: "specialist",
    responsibilities: ["Identify compliance risk", "Review data exposure", "Document policy concerns"],
    defaultTools: [...commonReadTools, "knowledge_base"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "ops.compliance.v1",
    promptTemplateId: "operations.legal_compliance.v1",
    canCreateTasks: true,
    canApprovePhaseGate: true,
    canRunExternalTools: false,
    mustNotDo: ["Provide legal certainty beyond evidence"]
  },
  {
    id: "customer_success_agent",
    name: "Customer Success Agent",
    department: "operations",
    level: "specialist",
    responsibilities: ["Write customer-facing notes", "Summarize impact", "Prepare support guidance"],
    defaultTools: [...commonReadTools, "knowledge_base"],
    permissionClasses: ["read", "draft", "external_comms"],
    outputSchemaId: "ops.customer_note.v1",
    promptTemplateId: "operations.customer_success.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Send external messages unless policy allows it"]
  },
  {
    id: "technical_writer",
    name: "Technical Writer Agent",
    department: "operations",
    level: "specialist",
    responsibilities: ["Write docs", "Write release notes", "Draft final report"],
    defaultTools: [...commonReadTools, "knowledge_base"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "ops.documentation.v1",
    promptTemplateId: "operations.technical_writer.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Document changes that are not supported by artifacts"]
  },
  {
    id: "knowledge_manager",
    name: "Knowledge Manager Agent",
    department: "operations",
    level: "specialist",
    responsibilities: ["Save durable memory", "Link memory to evidence", "Expire stale context"],
    defaultTools: [...commonReadTools, "knowledge_base"],
    permissionClasses: ["read", "draft"],
    outputSchemaId: "ops.memory.v1",
    promptTemplateId: "operations.knowledge_manager.v1",
    canCreateTasks: false,
    canApprovePhaseGate: false,
    canRunExternalTools: false,
    mustNotDo: ["Save raw secrets", "Save unverified assumptions as facts"]
  }
] as const satisfies readonly AgentRoleDefinition[];

export const ROLE_BY_ID = Object.fromEntries(
  ROLE_REGISTRY.map((role) => [role.id, role])
) as unknown as Record<RoleId, AgentRoleDefinition>;

export function getRole(roleId: RoleId): AgentRoleDefinition {
  return ROLE_BY_ID[roleId];
}
